name: liminal_launcher
description: "An Empathetech Android launcher."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  go_router: ^14.8.1
  intl: ^0.20.2
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

  # Community
  empathetech_flutter_ui:
    path: ../empathetech_flutter_ui
  feedback: ^3.1.0
  flutter_localized_locales: ^2.0.5
  flutter_platform_widgets: ^9.0.0
  permission_handler: ^12.0.1
  provider: ^6.1.5

dev_dependencies:
  dependency_validator: ^5.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/tmp-icon.jpg      

flutter_launcher_icons:
  image_path: assets/images/tmp-icon.jpg
  adaptive_icon_foreground: assets/images/tmp-icon.jpg
  adaptive_icon_background: "#000000"
  android: true
  ios: false
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  image: assets/images/tmp-icon.jpg
  color: "#000000"
  android: true
  ios: false
  web: false